### ISSUE TITLE
gives an error javac

### ISSUE THREAD

**Issue by vinayakumarr** [Eyasics/recon#1]
I followed your steps and when i try to execute ./setup weka_home_path I am getting the following error
![and](https://cloud.githubusercontent.com/assets/18217467/18348451/03a3d816-75e9-11e6-9af2-2d52cb025a05.png)

**Comment by Eyasics** [comment]
Hi vinayakumarr, weka_home_path should be replaced by the path you want to install.

**Comment by vinayakumarr** [comment]
insteat of weka_home_path, i had given ./setup /home/vinay but still gives the same error. It is a compiler error. Could you please tell how to correct it?

**Comment by Eyasics** [comment]
Could you let me know the version of your JDK and ant? 

A side note: Also make sure the `prepare_weka` has been executed when you do training. I didn't see it from your screenshot.

**Comment by vinayakumarr** [comment]
The above error is solved but this time getting different error. Could you please check this error
![error](https://cloud.githubusercontent.com/assets/18217467/18604394/b8550fa8-7c99-11e6-9f64-c0f9f37fd8a5.png)

**Comment by Eyasics** [comment]
you should do this in your installed directory(weka_home_path), instead of the original source code.

**Comment by vinayakumarr** [comment]
You had done only cros-validation. You didn't collect test dataset. Am I
right. Basically I work on ml. I just want to apply some other algorithms
to improve it. But I had found only train dataset. No test dataset
available. Also the dataset size is very small.

**Comment by Eyasics** [comment]
The code was doing cross-validation, and cross validation by definition splits the dataset into training part and testing part. Unfortunately, the only dataset we can publish is the traffic we did in our manual controlled experiment, and IRB restricts us from sharing users' data. You are more than welcome to do your own experiments, even publish anonymized dataset to contribute this work and benefit the community. If you have specific interests in mind and are looking for further collaboration, feel free to drop me an email. Thanks.
